name: Build Docker image
description: Build Docker image for a given service and push it to ghcr.io

inputs:
  service:
    description: Name of the service to build
    default: app
  context:
    description: Path to the Dockerfile context
    default: .
  platforms:
    description: Target platforms
    default: linux/arm64

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ inputs.platforms }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}/${{ inputs.service }}
    - name: Login to GitHub CR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        platforms: ${{ inputs.platforms }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
